### ISSUE TITLE
Disable the output of the gem in the rails console

### ISSUE THREAD

**Issue by samuelpismel** [ankane/cacheflow#1]
Hey guys, how are you?

I'm having a bad situation with this gem and the [message_bus](https://github.com/SamSaffron/message_bus) gem. The message_bus have some type of pub/sub and it make periodically request to redis, and the cacheflow gem catch and show all these requests on the output of rails server (ok) and in the rails console (not ok).

Showing these outputs in the console are a pretty annoying behavior and disturb me a lot when I am running commands in console. It can happen in the middle of a sentence/command and can break the experience of developing.

Would be nice to have a way to disable the output of the gem in the console or a way to disable/activate the gem (without removing it from gemfile).

Something like: `Cacheflow.silence!` to put in **.pryrc** ou **.irbrc** or to run manually in the console.

Example of my console (:sweat:):
![image](https://user-images.githubusercontent.com/1752499/65604073-2b304300-df7d-11e9-960b-dc6d7b718396.png)

**Comment by ankane** [comment]
Hey @samuelpismel, `Cacheflow.silence!` (and probably `unsilence!`) makes sense to me. Happy to review a PR.

**Comment by ankane** [comment]
Cleaning up issues, but the comment above still stands
