### ISSUE TITLE
Bolding log text warning

### ISSUE THREAD

**Issue by zhandao** [ankane/cacheflow#3]
Hi Kane,

I got a warning while using cacheflow:

`DEPRECATION WARNING: Bolding log text with a positional boolean is deprecated and will be removed in Rails 7.2. Use an option hash instead`

I think it might have something to do with this line:

https://github.com/ankane/cacheflow/blob/f4a7c9b45f6a73168fb4031531b59e72da9323dc/lib/cacheflow/redis.rb#L47

Thanks for your work~

**Comment by ankane** [comment]
Hi @zhandao, thanks for reporting! Fixed in the commit above. Will push a new release in a bit.
