### ISSUE TITLE
Does not support Rails 7.0+ cache format

### ISSUE THREAD

**Issue by mlarraz** [ankane/cacheflow#4]
Rails 7.0 introduced a new cache format: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format

This is off by default for older apps but on for newly generated ones.

When the new format is enabled, Cacheflow logs writes with the compressed value (a binary string) instead of the original value.

This isn't a big deal, but Rails 7.1 removes the old format, so eventually all Rails apps will be using the new one.

**Comment by ankane** [comment]
Hi @mlarraz, thanks for reporting. Fixed in the commit above.
